CREATE TABLE Books (
    Isbn VARCHAR(50) PRIMARY KEY,
    Title VARCHAR(40),
    Year INT
);

CREATE TABLE Author (
    Author_Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Full_Name VARCHAR(50)
);

CREATE TABLE Authorship (
    Isbn_Book VARCHAR(50),
    Author_Id INT, 
    PRIMARY KEY (Isbn_Book, Author_Id),
    FOREIGN KEY (Author_Id) REFERENCES Author (Author_Id),
    FOREIGN KEY (Isbn_Book) REFERENCES Books(Isbn)
);

CREATE TABLE Readers (
    reader_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Full_name VARCHAR(50),
    Phone VARCHAR(25)
);

CREATE TABLE Loan (
    Loan_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Reader_ID INT,
    Book_ISBN VARCHAR(50),
    loan_date DATE NOT NULL,
    due_date DATE NOT NULL,
    Actual_return_date DATE NULL,
    FOREIGN KEY (Reader_ID) REFERENCES Readers(reader_id),
    FOREIGN KEY (Book_ISBN) REFERENCES Books(Isbn)
);



INSERT INTO Readers (Full_name, Phone) VALUES
('Анна Петрова', '+7-900-111-22-33'),
('Иван Соколов', '+7-900-222-33-44'),
('Мария Ким', '+7-900-333-44-55'),
('Олег Васильев', '+7-900-444-55-66'),
('Тестовый Читатель', '+7-900-555-66-77');

INSERT INTO Books (Isbn, Title, Year) VALUES
('978-5-17-118366-8', 'Мастер и Маргарита', 1967),
('978-5-389-06256-6', 'Преступление и наказание', 1866),
('978-5-04-116716-3', 'Война и мир', 1869),
('978-5-699-12014-7', 'Золотой теленок', 1931),
('978-5-389-03713-7', 'Пикник на обочине', 1972);

INSERT INTO Author (Full_name) VALUES
('Михаил Булгаков'),
('Федор Достоевский'),
('Лев Толстой'),
('Илья Ильф'),
('Евгений Петров'),
('Аркадий Стругацкий'),
('Борис Стругацкий');

INSERT INTO Authorship (Isbn_Book, Author_Id) VALUES
('978-5-17-118366-8', (SELECT Author_Id FROM Author WHERE Full_name = 'Михаил Булгаков')),
('978-5-389-06256-6', (SELECT Author_Id FROM Author WHERE Full_name = 'Федор Достоевский')),
('978-5-04-116716-3', (SELECT Author_Id FROM Author WHERE Full_name = 'Лев Толстой')),
('978-5-699-12014-7', (SELECT Author_Id FROM Author WHERE Full_name = 'Илья Ильф')),
('978-5-699-12014-7', (SELECT Author_Id FROM Author WHERE Full_name = 'Евгений Петров')),
('978-5-389-03713-7', (SELECT Author_Id FROM Author WHERE Full_name = 'Аркадий Стругацкий')),
('978-5-389-03713-7', (SELECT Author_Id FROM Author WHERE Full_name = 'Борис Стругацкий'));

INSERT INTO Loan (Reader_ID, Book_ISBN, loan_date, due_date, Actual_return_date) VALUES
((SELECT reader_id FROM Readers WHERE Full_name = 'Анна Петрова'), '978-5-17-118366-8', '2026-09-01', '2026-09-15', '2026-09-10'),
((SELECT reader_id FROM Readers WHERE Full_name = 'Иван Соколов'), '978-5-389-06256-6', '2026-09-03', '2026-09-17', NULL),
((SELECT reader_id FROM Readers WHERE Full_name = 'Мария Ким'), '978-5-04-116716-3', '2026-09-05', '2026-09-19', '2026-09-18'),
((SELECT reader_id FROM Readers WHERE Full_name = 'Олег Васильев'), '978-5-699-12014-7', '2026-09-07', '2026-09-21', NULL),
((SELECT reader_id FROM Readers WHERE Full_name = 'Анна Петрова'), '978-5-389-03713-7', '2026-09-09', '2026-09-23', NULL),
((SELECT reader_id FROM Readers WHERE Full_name = 'Мария Ким'), '978-5-699-12014-7', '2026-08-20', '2026-09-03', '2026-09-01');

-- Проверяем выборки
SELECT * FROM Readers;
SELECT Title, Year FROM Books;
SELECT title, year 
FROM Books 
WHERE year >= 1801 AND year <= 1900;

SELECT title, year 
FROM Books 
WHERE year BETWEEN 1917 AND 1991;

SELECT * 
FROM Readers 
WHERE phone = '+7-900-111-22-33';

SELECT * 
FROM Readers 
WHERE full_name LIKE '%ов%';

SELECT * 
FROM Loan 
WHERE actual_return_date IS NULL;

SELECT title, year 
FROM Books 
ORDER BY title ASC;

SELECT * 
FROM Loan 
WHERE actual_return_date IS NULL
ORDER BY due_date ASC;

SELECT title, year 
FROM Books 
ORDER BY year ASC 
LIMIT 3;